### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [APTechnologies/The-Ultimate-Component-Storage-System#1]
Hello!

I found link to this project from https://hackaday.com/2021/01/05/the-last-component-storage-system-youd-ever-need/

Could you please add information about license of this repository — is it allowed to copy, change and use the code and CAD-files in any purpose?
It would be great to see any popular open source license.

**Comment by APTechnologies** [comment]
License is now added!

**Comment by vazhnov** [comment]
GPL v3 — great!
Thank you!
